import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		double avg = 0.0;
		int count2 = 0;
		int count3 = 0;
		int count4 = 0;
		int mode = 0;
		for (int j=0;j<T;j++)
		{
			boolean isGirl = false;
			boolean isBoy = false;
			int count = 0;
			while(isGirl==false || isBoy==false)
				{
					double rand = generator.nextDouble();
					if (rand<0.5)
						{
							isGirl=true;	
						}
					else 
						{
							isBoy=true;
						}
					count++;
				}
			avg+=count;
			if (count==2)
			{
				count2++;
			}
			else
				{
					if(count==3)
					{
						count3++;
					}
					else 
					{
						count4++;
					}
				}

		}
		avg = avg/T;
		mode=Math.max(count2, Math.max(count3,count4));
		System.out.println("Average: "+avg+" children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: "+count2);
		System.out.println("Number of families with 3 children: "+count3);
		System.out.println("Number of families with 4 or more children: "+count4);
		if (mode==count2)
		{
			System.out.println("The most common number of children is 2.");
		}
		else
			{
			if (mode==count3)
				{
				System.out.println("The most common number of children is 3.");
				}	
			else
				{
			
				System.out.println("The most common number of children is 4 or more.");
				}
			}
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		
	}
}
